### ISSUE TITLE
when creating entities, type is not written to database, so no checkins are available

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Bmore-Responsive#161] opened 2020-05-20 13:00 UTC
### User Story
As a user of the bmore-responsive project
I'd like to be able to create an entity with a supported type
So that I can make sure entities are created with the proper checkin questions available to them

### Acceptance Criteria
- [ ] When a facility is created with a type, the type is written to the Entities table type field so that checkin questions are available to the entity.  For example "Assisted Living Facility" is not written to Entities when creating a new Entity.  Manually updating type to "Assisted Living Facility" makes the questions available to the Facility
- [ ] Swagger doc is updated
- [ ] Postman collection is updated
- [ ] PR merged to `master`

### Notes
This is based on observations made when working with the simpsons data

**Comment by revjtanton** [comment] 2020-06-04 00:20
This is a duplicate of #145

**Closed by revjtanton** 2020-06-04 00:20 UTC
Labels: bug, duplicate
